apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-development   # name of deployment
  labels:
    pod: nginx  # name to reference for Service file.
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: nginx
  template:
    metadata:
      labels:
        pod: nginx
    spec:
      containers:
      - resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"
        name: nginx  # docker container name.
        image: nginx:alpine  # docker image to pull
        imagePullPolicy: IfNotPresent  # pull local first.
        ports:
          - name: nginx-port  # name of port 
            containerPort: 80  # port pod is listening on.
        # - name: discovery-port
        #   containerPort: 50000
    #   volumeMounts:
    #     - name: jenkins-vol
    #       mountPath: /var/jenkins_vol
    # volumes:
    #   - name: jenkins-vol
    #     emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx  # name of service. kubectl get service jenkins
spec:
  selector:  # Route service traffic to pods with label key:values matching this selector. 
    pod: nginx
  type: ClusterIP  #(ClusterIp (default), NodePort, LoadBalancer)
  ports:
    - protocol: TCP
      port: 80  # port to open on node for incoming request
      targetPort: 80  # port to pod is listening on.
      #nodePort: (30000-32767)  # Expose the node port to the outside world.  nodePort is a static IP on the node.
